[phases.setup]
commands = [
  "apk add --no-cache python3 py3-pip gcc musl-dev postgresql-dev",
  "pip3 install -r requirements.txt",
  "python create_db.py"
]

[phases.start]
commands = [
  "python api_server.py"
]

[env]
POSTGRES_HOST = "localhost"
POSTGRES_PORT = "5432"
POSTGRES_DB = "ecowitt"
POSTGRES_USER = "ecowitt_user"
POSTGRES_PASSWORD = "ecowitt_password"

[ports]
app = 5000
